{
 "title": "Application Telemetry (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "NodeJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "singlestat",
     "gridPos": { "x": 0, "y": 0, "w": 3, "h": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "number_of_requests" }
     ]
    },
    {
     "title": "% of successful requests",
     "type": "singlestat",
     "gridPos": { "x": 3, "y": 0, "w": 3, "h": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "number_of_successfull_requests / (number_of_successfull_requests + number_of_not_successfull_requests) * 100"
      }
     ]
    },
    {
     "title": "GQL Requests",
     "type": "singlestat",
     "gridPos": { "x": 6, "y": 0, "w": 3, "h": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "number_of_gql_requests" }
     ]
    }
   ]
  }
 ]
}